//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCommerceMVC.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Review.
        /// </summary>
        public static string Add_a_Review {
            get {
                return ResourceManager.GetString("Add a Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string Add_to_Cart {
            get {
                return ResourceManager.GetString("Add to Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string Address_is_required_ {
            get {
                return ResourceManager.GetString("Address is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string All_Categories {
            get {
                return ResourceManager.GetString("All Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string All_Products {
            get {
                return ResourceManager.GetString("All Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Already_have_an_account_ {
            get {
                return ResourceManager.GetString("Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amman, Jordan.
        /// </summary>
        public static string Amman__Jordan {
            get {
                return ResourceManager.GetString("Amman, Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availibility.
        /// </summary>
        public static string Availibility {
            get {
                return ResourceManager.GetString("Availibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on.
        /// </summary>
        public static string Based_on {
            get {
                return ResourceManager.GetString("Based on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/templates/aroma/vendors/bootstrap/bootstrap.min.css.
        /// </summary>
        public static string Bootstrap {
            get {
                return ResourceManager.GetString("Bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Now.
        /// </summary>
        public static string Browse_Now {
            get {
                return ResourceManager.GetString("Browse Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Policy.
        /// </summary>
        public static string Cancellation_Policy {
            get {
                return ResourceManager.GetString("Cancellation Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Products.
        /// </summary>
        public static string Cart_Products {
            get {
                return ResourceManager.GetString("Cart Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string Change_Avatar {
            get {
                return ResourceManager.GetString("Change Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account setting.
        /// </summary>
        public static string Change_your_account_setting {
            get {
                return ResourceManager.GetString("Change your account setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Check_Out {
            get {
                return ResourceManager.GetString("Check Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Now.
        /// </summary>
        public static string Checkout_Now {
            get {
                return ResourceManager.GetString("Checkout Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout your products.
        /// </summary>
        public static string Checkout_your_products {
            get {
                return ResourceManager.GetString("Checkout your products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string City_is_required_ {
            get {
                return ResourceManager.GetString("City is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string Click_here_to_Log_in {
            get {
                return ResourceManager.GetString("Click here to Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Confirm_Email {
            get {
                return ResourceManager.GetString("Confirm Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Us on LinkedIn.
        /// </summary>
        public static string Connect_Us_on_LinkedIn {
            get {
                return ResourceManager.GetString("Connect Us on LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Jomlah Jo Team..
        /// </summary>
        public static string Contact_Jomlah_Jo_Team_ {
            get {
                return ResourceManager.GetString("Contact Jomlah Jo Team.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        public static string Country_is_required_ {
            get {
                return ResourceManager.GetString("Country is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create a new account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string Create_an_Account {
            get {
                return ResourceManager.GetString("Create an Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer and shipping Details.
        /// </summary>
        public static string Customer_and_shipping_Details {
            get {
                return ResourceManager.GetString("Customer and shipping Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Chargres.
        /// </summary>
        public static string Delivery_Chargres {
            get {
                return ResourceManager.GetString("Delivery Chargres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Info.
        /// </summary>
        public static string Delivery_Info {
            get {
                return ResourceManager.GetString("Delivery Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Email_is_required_ {
            get {
                return ResourceManager.GetString("Email is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order ID.
        /// </summary>
        public static string Enter_Order_ID {
            get {
                return ResourceManager.GetString("Enter Order ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string Enter_verification_code {
            get {
                return ResourceManager.GetString("Enter verification code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Voucher/Promo Code.
        /// </summary>
        public static string Enter_Voucher_Promo_Code {
            get {
                return ResourceManager.GetString("Enter Voucher/Promo Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Categories.
        /// </summary>
        public static string Featured_Categories {
            get {
                return ResourceManager.GetString("Featured Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string Featured_Products {
            get {
                return ResourceManager.GetString("Featured Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        public static string Final_Amount {
            get {
                return ResourceManager.GetString("Final Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us on Instagram.
        /// </summary>
        public static string Follow_Us_on_Instagram {
            get {
                return ResourceManager.GetString("Follow Us on Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in 2020 by Jomlah Jo e-commerce Company, Jomlah Jo has come a long way from its beginnings in Amman-Jordan..
        /// </summary>
        public static string Founded_in_2020_by_Jomlah_Jo_e_commerce_Company__Jomlah_Jo_has_come_a_long_way_from_its_beginnings_in_Amman_Jordan_ {
            get {
                return ResourceManager.GetString("Founded in 2020 by Jomlah Jo e-commerce Company, Jomlah Jo has come a long way fr" +
                        "om its beginnings in Amman-Jordan.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Advanced Internet Solutions.
        /// </summary>
        public static string Future_Advanced_Internet_Solutions {
            get {
                return ResourceManager.GetString("Future Advanced Internet Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get exciting discounts. Apply promo &apos;Winter50&apos;.
        /// </summary>
        public static string Get_exciting_discounts__Apply_promo__Winter50_ {
            get {
                return ResourceManager.GetString("Get exciting discounts. Apply promo \'Winter50\'", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Promo/Voucher ?.
        /// </summary>
        public static string Have_Promo_Voucher__ {
            get {
                return ResourceManager.GetString("Have Promo/Voucher ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string In_Stock {
            get {
                return ResourceManager.GetString("In Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("Invalid login attempt.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid promo/voucher..
        /// </summary>
        public static string Invalid_promo_voucher_ {
            get {
                return ResourceManager.GetString("Invalid promo/voucher.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOD.
        /// </summary>
        public static string JOD {
            get {
                return ResourceManager.GetString("JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jomlah Jo.
        /// </summary>
        public static string Jomlah_Jo {
            get {
                return ResourceManager.GetString("Jomlah Jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jomlah Jo Have Everything You desire.
        /// </summary>
        public static string Jomlah_Jo_Have_Everything_You_desire {
            get {
                return ResourceManager.GetString("Jomlah Jo Have Everything You desire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Products.
        /// </summary>
        public static string Latest_Products {
            get {
                return ResourceManager.GetString("Latest Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave your Comment.
        /// </summary>
        public static string Leave_your_Comment {
            get {
                return ResourceManager.GetString("Leave your Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like And Get in Touch on Facebook.
        /// </summary>
        public static string Like_And_Get_in_Touch_on_Facebook {
            get {
                return ResourceManager.GetString("Like And Get in Touch on Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN TO ACCOUNT.
        /// </summary>
        public static string LOGIN_TO_ACCOUNT {
            get {
                return ResourceManager.GetString("LOGIN TO ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With.
        /// </summary>
        public static string Login_With {
            get {
                return ResourceManager.GetString("Login With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Us on WhatsApp.
        /// </summary>
        public static string Message_Us_on_WhatsApp {
            get {
                return ResourceManager.GetString("Message Us on WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to our website?.
        /// </summary>
        public static string New_to_our_website_ {
            get {
                return ResourceManager.GetString("New to our website?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories available..
        /// </summary>
        public static string No_categories_available_ {
            get {
                return ResourceManager.GetString("No categories available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments found..
        /// </summary>
        public static string No_comments_found_ {
            get {
                return ResourceManager.GetString("No comments found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Orders found..
        /// </summary>
        public static string No_Orders_found_ {
            get {
                return ResourceManager.GetString("No Orders found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products in the cart.
        /// </summary>
        public static string No_products_in_the_cart {
            get {
                return ResourceManager.GetString("No products in the cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Amount.
        /// </summary>
        public static string Order_Amount {
            get {
                return ResourceManager.GetString("Order Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Order_Details {
            get {
                return ResourceManager.GetString("Order Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string Order_History {
            get {
                return ResourceManager.GetString("Order History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_ID {
            get {
                return ResourceManager.GetString("Order ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Unique Code.
        /// </summary>
        public static string Order_Unique_Code {
            get {
                return ResourceManager.GetString("Order Unique Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders section in profile.
        /// </summary>
        public static string orders_section_in_profile {
            get {
                return ResourceManager.GetString("orders section in profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Jordanian Webstore.
        /// </summary>
        public static string Our_Jordanian_Webstore {
            get {
                return ResourceManager.GetString("Our Jordanian Webstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Stock.
        /// </summary>
        public static string Out_Of_Stock {
            get {
                return ResourceManager.GetString("Out Of Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Average.
        /// </summary>
        public static string Overall_Average {
            get {
                return ResourceManager.GetString("Overall Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via Cash On Delivery.
        /// </summary>
        public static string Pay_via_Cash_On_Delivery {
            get {
                return ResourceManager.GetString("Pay via Cash On Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via Credit Card.
        /// </summary>
        public static string Pay_via_Credit_Card {
            get {
                return ResourceManager.GetString("Pay via Credit Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string Place_Order {
            get {
                return ResourceManager.GetString("Place Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed On Date.
        /// </summary>
        public static string Placed_On_Date {
            get {
                return ResourceManager.GetString("Placed On Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country Code.
        /// </summary>
        public static string Please_Select_Country_Code {
            get {
                return ResourceManager.GetString("Please Select Country Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Range.
        /// </summary>
        public static string Price_Range {
            get {
                return ResourceManager.GetString("Price Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice.
        /// </summary>
        public static string Print_Invoice {
            get {
                return ResourceManager.GetString("Print Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        public static string Product_Categories {
            get {
                return ResourceManager.GetString("Product Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Descreption.
        /// </summary>
        public static string Product_Descreption {
            get {
                return ResourceManager.GetString("Product Descreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Reviews.
        /// </summary>
        public static string Product_Reviews {
            get {
                return ResourceManager.GetString("Product Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Specification.
        /// </summary>
        public static string Product_Specification {
            get {
                return ResourceManager.GetString("Product Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string Quick_Links {
            get {
                return ResourceManager.GetString("Quick Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Account.
        /// </summary>
        public static string Recover_Account {
            get {
                return ResourceManager.GetString("Recover Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Policy.
        /// </summary>
        public static string Refund_Policy {
            get {
                return ResourceManager.GetString("Refund Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string Related_Products {
            get {
                return ResourceManager.GetString("Related Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remmeber Me.
        /// </summary>
        public static string Remmeber_Me {
            get {
                return ResourceManager.GetString("Remmeber Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string Reset_your_password_ {
            get {
                return ResourceManager.GetString("Reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your profile.
        /// </summary>
        public static string Review_your_profile {
            get {
                return ResourceManager.GetString("Review your profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by OrderID.
        /// </summary>
        public static string Search_by_OrderID {
            get {
                return ResourceManager.GetString("Search by OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        public static string Search_Filters {
            get {
                return ResourceManager.GetString("Search Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Latest Products on Jomlah Jo.
        /// </summary>
        public static string Search_Latest_Products_on_Jomlah_Jo {
            get {
                return ResourceManager.GetString("Search Latest Products on Jomlah Jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Products.
        /// </summary>
        public static string Search_Products {
            get {
                return ResourceManager.GetString("Search Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Avatar.
        /// </summary>
        public static string Select_Avatar {
            get {
                return ResourceManager.GetString("Select Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Order Status.
        /// </summary>
        public static string Select_by_Order_Status {
            get {
                return ResourceManager.GetString("Select by Order Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop with us now.
        /// </summary>
        public static string Shop_with_us_now {
            get {
                return ResourceManager.GetString("Shop with us now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. No Products found..
        /// </summary>
        public static string Sorry__No_Products_found_ {
            get {
                return ResourceManager.GetString("Sorry. No Products found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. This promo/voucher has expired..
        /// </summary>
        public static string Sorry__This_promo_voucher_has_expired_ {
            get {
                return ResourceManager.GetString("Sorry. This promo/voucher has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! We can not track your order details..
        /// </summary>
        public static string Sorry__We_can_not_track_your_order_details_ {
            get {
                return ResourceManager.GetString("Sorry! We can not track your order details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By: Latest Products.
        /// </summary>
        public static string Sort_By__Latest_Products {
            get {
                return ResourceManager.GetString("Sort By: Latest Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By: Product Names.
        /// </summary>
        public static string Sort_By__Product_Names {
            get {
                return ResourceManager.GetString("Sort By: Product Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/templates/aroma/css/style.css.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Us on YouTube.
        /// </summary>
        public static string Subscribe_Us_on_YouTube {
            get {
                return ResourceManager.GetString("Subscribe Us on YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Terms___Conditions {
            get {
                return ResourceManager.GetString("Terms & Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You. Your order has been placed. You can access your order details anytime in your.
        /// </summary>
        public static string Thank_You__Your_order_has_been_placed__You_can_access_your_order_details_anytime_in_your {
            get {
                return ResourceManager.GetString("Thank You. Your order has been placed. You can access your order details anytime " +
                        "in your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string Thank_you_for_confirming_your_email__Please {
            get {
                return ResourceManager.GetString("Thank you for confirming your email. Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks..
        /// </summary>
        public static string Thanks_ {
            get {
                return ResourceManager.GetString("Thanks.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no comments on this products..
        /// </summary>
        public static string There_are_no_comments_on_this_products_ {
            get {
                return ResourceManager.GetString("There are no comments on this products.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be updated with all our hot offers.
        /// </summary>
        public static string to_be_updated_with_all_our_hot_offers {
            get {
                return ResourceManager.GetString("to be updated with all our hot offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Order.
        /// </summary>
        public static string Track_Order {
            get {
                return ResourceManager.GetString("Track Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet And Follow on Twitter.
        /// </summary>
        public static string Tweet_And_Follow_on_Twitter {
            get {
                return ResourceManager.GetString("Tweet And Follow on Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To 50% Off.
        /// </summary>
        public static string Up_To_50__Off {
            get {
                return ResourceManager.GetString("Up To 50% Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        public static string Updated_On {
            get {
                return ResourceManager.GetString("Updated On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Use_a_local_account_to_log_in_ {
            get {
                return ResourceManager.GetString("Use a local account to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoy our products as much as we enjoy offering them to you. If you have any questions or comments, please don&apos;t hesitate to contact us..
        /// </summary>
        public static string We_hope_you_enjoy_our_products_as_much_as_we_enjoy_offering_them_to_you__If_you_have_any_questions_or_comments__please_don_t_hesitate_to_contact_us_ {
            get {
                return ResourceManager.GetString("We hope you enjoy our products as much as we enjoy offering them to you. If you h" +
                        "ave any questions or comments, please don\'t hesitate to contact us.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We serve customers everywhere in Jordan, welcomed with great openness..
        /// </summary>
        public static string We_serve_customers_everywhere_in_Jordan__welcomed_with_great_openness_ {
            get {
                return ResourceManager.GetString("We serve customers everywhere in Jordan, welcomed with great openness.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To.
        /// </summary>
        public static string Welcome_To {
            get {
                return ResourceManager.GetString("Welcome To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jomlah Jo, your number one source for all things. We&apos;re dedicated to give you the very best of products you may need..
        /// </summary>
        public static string Welcome_to_Jomlah_Jo__your_number_one_source_for_all_things__We_re_dedicated_to_give_you_the_very_best_of_products_you_may_need_ {
            get {
                return ResourceManager.GetString("Welcome to Jomlah Jo, your number one source for all things. We\'re dedicated to g" +
                        "ive you the very best of products you may need.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Sale.
        /// </summary>
        public static string Winter_Sale {
            get {
                return ResourceManager.GetString("Winter Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your comment here..
        /// </summary>
        public static string Write_your_comment_here_ {
            get {
                return ResourceManager.GetString("Write your comment here.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check the status of your order. Please enter the order ID and you will get information related to your order..
        /// </summary>
        public static string You_can_check_the_status_of_your_order__Please_enter_the_order_ID_and_you_will_get_information_related_to_your_order_ {
            get {
                return ResourceManager.GetString("You can check the status of your order. Please enter the order ID and you will ge" +
                        "t information related to your order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string You_do_not_have_a_local_username_password_for_this_site__Add_a_local_account_so_you_can_log_in_without_an_external_login_ {
            get {
                return ResourceManager.GetString("You do not have a local username/password for this site. Add a local account so y" +
                        "ou can log in without an external login.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to leave comments..
        /// </summary>
        public static string You_need_to_login_to_leave_comments_ {
            get {
                return ResourceManager.GetString("You need to login to leave comments.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        public static string Your_Cart {
            get {
                return ResourceManager.GetString("Your Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been placed..
        /// </summary>
        public static string Your_order_has_been_placed_ {
            get {
                return ResourceManager.GetString("Your order has been placed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string Your_password_has_been_reset__Please {
            get {
                return ResourceManager.GetString("Your password has been reset. Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rating.
        /// </summary>
        public static string Your_Rating {
            get {
                return ResourceManager.GetString("Your Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total bill is.
        /// </summary>
        public static string Your_total_bill_is {
            get {
                return ResourceManager.GetString("Your total bill is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code is required..
        /// </summary>
        public static string Zip_Code_is_required_ {
            get {
                return ResourceManager.GetString("Zip Code is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
